/**
 * Builds downloadable, double-click Songstarr packages for non-technical users.
 *
 *   npm run release                       # all platforms
 *   npm run release -- --targets linux-x64,windows-x64
 *
 * Output: release/out/Songstarr-<version>-<platform>.zip, each containing the executable,
 * "START HERE" instructions and third-party licences. Requires Bun (https://bun.sh) for
 * `bun build --compile`, which can cross-compile every target from one machine.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync, copyFileSync, chmodSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { startHereText, type Platform } from './startHere.ts';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'release', 'out');
const GEN = path.join(ROOT, 'release', 'generated');
const version = (JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8')) as { version: string }).version;

interface Target {
  id: string;
  bunTarget: string;
  platform: Platform;
  exe: string;
}
const TARGETS: Target[] = [
  { id: 'windows-x64', bunTarget: 'bun-windows-x64', platform: 'windows', exe: 'Songstarr.exe' },
  { id: 'macos-arm64', bunTarget: 'bun-darwin-arm64', platform: 'macos', exe: 'Songstarr' },
  { id: 'macos-x64', bunTarget: 'bun-darwin-x64', platform: 'macos', exe: 'Songstarr' },
  { id: 'linux-x64', bunTarget: 'bun-linux-x64', platform: 'linux', exe: 'Songstarr' },
  { id: 'linux-arm64', bunTarget: 'bun-linux-arm64', platform: 'linux', exe: 'Songstarr' },
];

// Only what the browser actually loads. Licence texts go into the zip instead.
const SKIP_ASSET = /\.(eot|otf|svg|txt|md)$|(^|\/)LICENSE$|\.sf3$/;

function findBun(): string {
  const candidates = [process.env.BUN, path.join(os.homedir(), '.bun', 'bin', process.platform === 'win32' ? 'bun.exe' : 'bun'), 'bun'];
  for (const c of candidates) {
    if (!c) continue;
    try {
      execFileSync(c, ['--version'], { stdio: 'ignore' });
      return c;
    } catch {
      /* try next */
    }
  }
  throw new Error('Bun is required to build release executables. Install it from https://bun.sh');
}

function walk(dir: string, base = dir): string[] {
  return readdirSync(dir).flatMap((name) => {
    const full = path.join(dir, name);
    return statSync(full).isDirectory() ? walk(full, base) : [path.relative(base, full).split(path.sep).join('/')];
  });
}

function run(cmd: string, args: string[], cwd = ROOT): void {
  execFileSync(cmd, args, { cwd, stdio: 'inherit', shell: process.platform === 'win32' });
}

const argTargets = process.argv.find((_, i) => process.argv[i - 1] === '--targets')?.split(',');
const targets = argTargets ? TARGETS.filter((t) => argTargets.includes(t.id)) : TARGETS;
if (!targets.length) throw new Error(`No matching targets. Choose from: ${TARGETS.map((t) => t.id).join(', ')}`);

const bun = findBun();
console.log(`Building Songstarr ${version} for ${targets.map((t) => t.id).join(', ')}`);

// 1. Build the UI.
run('npm', ['run', 'build']);

// 2. Generate the executable's entry point with the UI + demo songs embedded as base64.
const distDir = path.join(ROOT, 'dist');
const assets: Record<string, string> = {};
for (const rel of walk(distDir)) {
  if (!SKIP_ASSET.test(rel)) assets[rel] = readFileSync(path.join(distDir, rel)).toString('base64');
}
const demoDir = path.join(ROOT, 'demo');
const demo: Record<string, string> = {};
for (const name of readdirSync(demoDir)) demo[name] = readFileSync(path.join(demoDir, name)).toString('base64');

rmSync(GEN, { recursive: true, force: true });
mkdirSync(GEN, { recursive: true });
const entry = path.join(GEN, 'entry.ts');
writeFileSync(
  entry,
  `// Generated by release/build.ts. Do not edit.\n` +
    `import { runLauncher } from '../launcher.ts';\n` +
    `await runLauncher(${JSON.stringify({ version, assets, demo })});\n`,
);
console.log(`Embedded ${Object.keys(assets).length} UI files and ${Object.keys(demo).length} demo files`);

// 3. Compile + package each target.
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
const licences = [
  ['LICENSE', path.join(ROOT, 'LICENSE')],
  ['alphaTab-LICENSE-MPL-2.0.txt', path.join(ROOT, 'node_modules/@coderline/alphatab/LICENSE')],
  ['Bravura-font-OFL.txt', path.join(ROOT, 'node_modules/@coderline/alphatab/dist/font/Bravura-OFL.txt')],
  ['Sonivox-soundfont-LICENSE.txt', path.join(ROOT, 'node_modules/@coderline/alphatab/dist/soundfont/LICENSE')],
] as const;

for (const t of targets) {
  const name = `Songstarr-${version}-${t.id}`;
  const dir = path.join(OUT, name);
  mkdirSync(path.join(dir, 'licenses'), { recursive: true });
  const exePath = path.join(dir, t.exe);
  const compileArgs = ['build', '--compile', '--minify', `--target=${t.bunTarget}`, entry, '--outfile', exePath];
  // Bun only supports Windows metadata flags when compiling on Windows itself.
  if (t.platform === 'windows' && process.platform === 'win32') compileArgs.push('--windows-title=Songstarr');
  run(bun, compileArgs);
  if (t.platform !== 'windows') chmodSync(exePath, 0o755);
  if (t.platform === 'macos') {
    // Bun's cross-compiled macOS binaries carry an invalid ad-hoc signature (macOS says "damaged" or
    // kills them on launch). On a Mac we can fix that here; elsewhere the Release workflow's macOS job does.
    if (process.platform === 'darwin') {
      run('codesign', ['--remove-signature', exePath]);
      run('codesign', ['--force', '--sign', '-', '--identifier', 'app.songstarr', exePath]);
      run('codesign', ['--verify', '--strict', exePath]);
    } else {
      console.warn(`! ${t.id}: must be re-signed on a Mac before it can run (the Release workflow does this).`);
    }
  }

  const text = startHereText(t.platform, version);
  // Windows Notepad versions before 2018 need CRLF line endings.
  writeFileSync(path.join(dir, 'START HERE.txt'), t.platform === 'windows' ? text.replace(/\n/g, '\r\n') : text);
  for (const [dest, src] of licences) if (existsSync(src)) copyFileSync(src, path.join(dir, 'licenses', dest));

  // zip keeps the executable bit, so macOS/Linux users can double-click right after unzipping.
  const zipFile = `${name}.zip`;
  rmSync(path.join(OUT, zipFile), { force: true });
  run('zip', ['-qry', zipFile, name], OUT);
  console.log(`✓ ${zipFile} (${(statSync(path.join(OUT, zipFile)).size / 1e6).toFixed(1)} MB)`);
}
console.log(`\nDone. Packages are in ${path.relative(ROOT, OUT)}/`);
